### ISSUE TITLE
README.md 部分連結失效

### ISSUE THREAD

**Issue by bestlong** [alincode/learngeb#12]
- 動手玩 Java 專案建置工具：以 Gradle 與 Docker 為例
- JCConf Taiwan 2015
- JCConf Taiwan 2014

The page you were looking for doesn't exist.

**Comment by alincode** [comment]
已經修正，但是暫時因為 gitbook 的權限問題無法部署，囧

**Comment by alincode** [comment]
@bestlong 部署了
